#!/bin/ash /etc/rc.common

START=99

start() {
	sleep 5   # make sure boot process is done, no more console msgs
	echo "eth0 The app is ready to start"
	sh /autorun.sh
}

stop() {
	kill -9 `ps | grep "sh /autorun.sh" | awk '{if(NR==1)print$1}'`
	kill -9 `ps | grep "apclient" | awk '{if(NR==1)print$1}'`
}